export const ACCOUNT_ALREADY_EXISTS_ERROR_CODE = 11000;
export const NOT_FOUND_STATUS = 404;
export const SERVER_ERROR_STATUS = 500;
export const FORBIDDEN_STATUS = 403;
export const CONFLICT_STATUS = 409;
