export const ACCOUNT_ALREADY_EXISTS_ERROR_CODE = 11000;
export const NOT_FOUND_STATUS = 404;
export const SERVER_ERROR_STATUS = 500;
export const FORBIDDEN_STATUS = 403;
export const CONFLICT_STATUS = 409;
export const RATE_LIMIT_EXCEEDED_STATUS = 429;
export const BAD_REQUEST_STATUS = 400;
